name: BanGUI
version: '${project.version}'
main: bangui.bangui.BanGUI
api-version: 1.17
authors: [ LousyBoi ]
description: A simple BanGUI plugin for your spigot server
commands:
  bangui:
    description: Opens the BanGUI menu
  BGhelp:
    description: show a list of commands
  Staff:
    description: Opens the staff menu
  onlineplayers:
    description: Opens a list of online players
  checktopplayers:
    description: Check the players who can see the OP players in the ban and kick menus
