name: BanGUI
version: '${project.version}'
main: bangui.bangui.BanGUI
api-version: 1.17
authors: [ LousyBoi ]
description: A simple BanGUI plugin for your spigot server
commands:
  report:
    description: Opens the ReportGUI menu
    usage: /report
  nv:
    description: Gives player night vision for when spectating other players
    usage: /nv
    permission: bangui.nv
  clearnv:
    description: Clears the players night vision
    usage: /clearnv
    permission: bangui.nv
  lockdown:
    description: Toggles the server's lockdown state
    usage: /lockdown
    permission: bangui.lockdown, bangui.LogInDuringLockdown
  bgreload:
    description: Reloads config
    usage: /bgreload
    permission: bangui.reload
  banGUI:
    description: Opens BanGUI
    usage: /banGUI [Player]
    permission: bangui.banMenu
  kickGUI:
    description: Opens KickGUI
    usage: /kickGUI [Player]
    permission: bangui.kickMenu
  sc:
    description: Talks in the staff chat
    usage: /sc [Message]
    permission: bangui.staffchat
  vanish:
    description: Vanishes you from the world
    usage: /vanish
    permission: bangui.vanish
    aliases: v
  freeze:
    description: Freezes a player
    usage: /freeze [Player]
    permission: bangui.freeze
  randomTP:
    description: TPs you to a random player
    usage: /randomTP
    permission: bangui.randomTP
  invsee:
    description: See other players inventories
    usage: /invsee [Target Player]
    permission: bangui.invsee
  onlinePlayers:
    description: Allows staff to see all online players
    usage: /onlinePlayers
    permission: bangui.onlinePlayers
  broadcast:
    description: Broadcast a message to the whole server
    usage: /broadcast [Message]
    permission: bangui.broadcast
    aliases: bc